variables:
  COMPOSER_ALLOW_SUPERUSER: 1
  COMPOSER_NO_INTERACTION: 1
  CACHE_COMPRESSION_LEVEL: "fastest"
  FF_USE_FASTZIP: 1

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/

stages:
  - build
  - code
  - test

# Install project dependencies
install:
  stage: build
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress

# Twig linter
lint:twig:
  stage: code
  dependencies:
    - install
  allow_failure: true
  script:
    - bin/console lint:twig templates

# YAML linter
lint:yaml:
  stage: code
  dependencies:
    - install
  allow_failure: true
  script:
    - bin/console lint:yaml config

# Check PHP code
code-fixer:
  stage: code
  dependencies:
    - install
  allow_failure: true
  script:
    - vendor/bin/php-cs-fixer fix --diff --dry-run

# Load fixtures and execute tests
phpunit:
  stage: test
  dependencies:
    - install
  script:
    - composer test

